[build]
target = "index.html"
dist = "dist"
public_url = "/"

[[assets]]
file = "static/styles.css"

[[assets]]
file = "static/manifest.json"

[[assets]]
file = "static/sw.js"

[watch]
watch = ["src", "static"]
ignore = ["dist"]

[serve]
address = "127.0.0.1"
port = 8080
open = false

[clean]
dist = "dist"

[[hooks]]
stage = "pre_build"
command = "wasm-pack"
command_arguments = ["--version"]

[tools]
sass = "2.0.0"
wasm-bindgen = "0.2.100"