services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: ${ENVIRONMENT:-production}
    ports:
      - "${FRONTEND_PORT:-8080}:80"
    environment:
      - VISION_SERVICE_URL=http://vision-service:2001
      - QUEUE_SERVICE_URL=http://queue-worker:8001
    depends_on:
      - vision-service
    networks:
      - app-network

  vision-service:
    build:
      context: ./backend/vision-service
      dockerfile: Dockerfile
    ports:
      - "${VISION_SERVICE_PORT:-2001}:2001"
    environment:
      - PORT=2001
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    networks:
      - app-network

  queue-worker:
    build:
      context: ./backend/queue-worker
      dockerfile: Dockerfile
    ports:
      - "${QUEUE_WORKER_PORT:-8001}:8001"
    environment:
      - PORT=8001
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
