# AI4Thai API Gateway - Complete Default Configuration

[server]
host = "0.0.0.0"
port = 3000
workers = 2
max_connections = 1000

[redis]
url = "redis://localhost:6379"
max_connections = 10
connection_timeout_seconds = 5
command_timeout_seconds = 10
retry_attempts = 3
retry_delay_ms = 100

[services.vision]
name = "vision-service"
base_url = "http://localhost:2001"
timeout_seconds = 30
health_check_path = "/health"
health_check_interval_seconds = 30
max_concurrent_requests = 10

[services.llm]
name = "llm-service"
base_url = "http://localhost:2002"
timeout_seconds = 60
health_check_path = "/health"
health_check_interval_seconds = 30
max_concurrent_requests = 5

[services.discovery]
enabled = false
registry_url = "http://localhost:8500"
service_name = "api-gateway"
service_port = 3000
health_check_interval_seconds = 30
deregister_on_shutdown = true

[services.circuit_breaker]
failure_threshold = 5
recovery_timeout_seconds = 60
half_open_max_calls = 3
min_request_threshold = 10

[services.retry]
max_attempts = 3
initial_delay_ms = 100
max_delay_ms = 5000
multiplier = 2.0
jitter = true

[external_apis]
default_timeout_seconds = 30
default_retry_attempts = 3

[external_apis.ai4thai]
api_key = ""
api_url = "https://api.ai4thai.org/v1"
timeout_seconds = 30
rate_limit_per_minute = 60
cache_duration_hours = 24

[external_apis.ai4thai.tts]
default_voice_th = "th-TH-Premwadee"
default_voice_en = "en-US-Jenny"
supported_voices = ["th-TH-Premwadee", "th-TH-Niran", "en-US-Jenny", "en-US-Guy"]
max_text_length = 5000
audio_format = "mp3"
sample_rate = 22050
speed_range = [0.5, 2.0]
pitch_range = [0.5, 2.0]

[external_apis.ai4thai.asr]
supported_languages = ["th", "th-TH", "en", "en-US"]
max_audio_duration_seconds = 300
max_file_size_mb = 25
supported_formats = ["mp3", "wav", "webm", "m4a", "ogg"]
sample_rates = [16000, 22050, 44100, 48000]
enable_punctuation = true
enable_timestamps = true
language_detection = true

[external_apis.weather]
provider = "OpenWeatherMap"
api_key = ""
api_url = "https://api.openweathermap.org/data/2.5"
default_location = "Bangkok,TH"
cache_duration_minutes = 30
forecast_days = 7
rate_limit_per_hour = 1000

[logging]
level = "info"
format = "json"
output = "stdout"
