# AI4Thai API Gateway - Development Configuration

[server]
host = "0.0.0.0"
port = 3000

[redis]
url = "redis://localhost:6379"

[services]
# Use external AI4Thai services for development
vision_service_url = "https://vision-api.ai4thai.com"
llm_service_url = "https://llm-api.ai4thai.com"
queue_worker_url = "http://localhost:2003"

[logging]
level = "debug"
format = "pretty"
output = "stdout"
